<html>
<head>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="style.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
</head>
<body>
<div id="container">
    <form action="main.php?action=add" method="POST" class="form-inline">
        <div class="form-group mb-2">
            <label for="staticEmail2" class="sr-only">Email</label>
            <input type="text" class="form-control" name="pseudo" placeholder="Pseudo">
        </div>
        <div class="form-group mx-sm-3 mb-2">
            <label for="comment" class="sr-only">Tweet</label>
            <textarea class="form-control" rows="5" name="content" id="comment"></textarea>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Send Tweet</button>
    </form>
</div>
<div class="inline">
<form id="editForm" action="main.php?action=edit" method="POST" class="form-inline">
    <div class="form-group mb-2">
        <label for="staticEmail2" class="sr-only">Email</label>
        <input type="text" id="pseudoEdit" class="form-control" name="pseudo" placeholder="Pseudo">
    </div>
    <div class="form-group mx-sm-3 mb-2">
        <label for="comment" class="sr-only">Tweet</label>
        <textarea class="form-control" id="contentEdit" rows="5" name="content" id="comment"></textarea>
    </div>
    <button type="submit" class="btn btn-primary mb-2">Update Tweet</button>
</form>
</div>
<hr>
<div id="tweetContainer">
    <?php
        foreach($tweets as $tweet): ?>
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <small><?= $tweet->getDate()?></small>
                    <h5 class="card-title"><?= $tweet->getPseudo()?></h5>
                    <p class="card-text"><?= $tweet->getContent()?></p>
                    <a  class="edit" href="main.php?action=edit&id=<?= $tweet->getId() ?>"><i data-id="<?= $tweet->getId() ?>" class="far fa-edit"></i></a>
                    <a href="main.php?action=delete&id=<?= $tweet->getId() ?>"><i class="fas fa-times"></i></a>
                </div>
            </div>

    <?php endforeach; ?>
</div>
<script src="main.js"></script>
</body>
</html>