<?php

include "header.php";

?>
<main>
		<h1><i class="fas fa-pencil-alt"></i> Ajouter un auteur</h1>
		<p><a href="homePage.php"><i class="fas fa-reply"></i> Retour à l'accueil</a></p>
		<img src="images/portrait.jpg" alt="portrait">
		
		<form action="addAuthor.php" method="post">
			<fieldset>
				<legend><i class="fas fa-file"></i> Nouvel auteur</legend>
				<label for="nom">Nom : </label>
				<input type="text" id="nom" name="nom">

				<label for="prenom">Article : </label>
				<input type="text" id="prenom" name="prenom">
						
				<div class="button">
					<button type="submit" id="add">Enregistrer</button>
					<a href="admin.php" id="cancel">Annuler</a>
				</div>
			</fieldset>
		</form>		
	</main>
