<?php

include "header.php";

?>
<main>
	<h1><i class="fas fa-pencil-alt"></i> Ajouter une catégorie</h1>
	<p><a href="homePage.php"><i class="fas fa-reply"></i> Retour à l'accueil</a></p>
	<img src="images/portrait.jpg" alt="portrait">
	
	<form action="addCategory.php" method="post">
		<fieldset>
			<legend><i class="fas fa-file"></i> Nouvel catégorie</legend>
			<label for="nom">Nom de la nouvelle catégorie : </label>
			<input type="text" id="nom" name="categoryName">
			
			<div class="button">
				<button type="submit" id="add">Enregistrer</button>
				<a href="admin.php" id="cancel">Annuler</a>
			</div>
		</fieldset>
	</form>		
</main>
