<?php

include "header.php";

?>

<main>
	<h1><i class="fas fa-pencil-alt"></i> Rédiger un article</h1>
	<p><a href="homePage.php"><i class="fas fa-reply"></i> Retour à l'accueil</a></p>
	<img src="images/portrait.jpg" alt="portrait">
	
	<form action="newArticle.php" method="post">
		<fieldset>
			<legend><i class="fas fa-file"></i> Nouvel article</legend>
			<label for="titre">Titre : </label>
			<input type="text" id="titre" name="titre">

			<label for="article">Article : </label>
			<textarea name="article" id="article" cols="30" rows="10"></textarea>

			<label for="auteur">Auteur : </label>
			<select name="auteur" id="auteur">
				<option selected disable>Auteur</option>
				<?php foreach ($auteurs as $auteur) :?>
					<option value="<?=$auteur["id"];?>"><?=$auteur["firstName"].$auteur["lastName"]?></option>
				<?php endforeach; ?>
			</select>
				
			<label for="categorie">Catégorie : </label>
			<select name="categorie" id="categorie">
				<option selected disable>Catégorie</option>
				<?php foreach ($categories as $category) :?>
					<option value="<?=$category["id"];?>"><?=$category["name"];?></option>
				<?php endforeach; ?>
			</select>
			
			<div class="button">
				<button type="submit" id="add">Enregistrer</button>
				<a href="admin.php" id="cancel">Annuler</a>
			</div>
		</fieldset>
	</form>		
</main>
