<?php

include "header.php";

?>

<main>
	<section class="entete">
		<h1><i class="fas fa-home"><a href="homePage.php"></i> Accueil</a></h1>
		<img src="images/portrait.jpg" alt="portrait">
	</section>
	<form action="newMember.php" method="post">
		<fieldset>
			<legend>Créer un nouveau compte</legend>
			<label for="pseudo">Pseudo : </label>
			<input type="text" name="pseudo" required>

			<label for="password">Mot de passe :</label>
			<input type="password" name="password" required>

			<label for="password">Confirmer mot de passe :</label>
			<input type="password" name="confpassword" required>

			<label for="password">Adresse e-mail :</label>
			<input type="text" name="mail" required>

			<div class="button">
				<button type="submit" id="add">Enregistrer</button>
				<a href="homePage.php" id="cancel">Annuler</a>
			</div>
		</fieldset>
	</form>
	<?= $erreur; ?>
</main>	
