// Afficher le contenu des posts sur la home page
<html>
<body>
	<p><?= $post["Title"]; ?></p>
	<p><?= $post["Contents"]; ?></p>
	<p><?= $post["CreationTimestamp"]; ?></p>
	<p><?= $post["FirstName"]." ".$post["LastName"]; ?></p>

	<?php foreach($commentaires as $comment) : ?>
		<p><?= $comment["NickName"]; ?></p>
		<p><?= $comment["Contents"]; ?></p>
	<?php endforeach; ?>

	<form action="addComment.php?articleID=<?= $_GET["articleID"] ?>" method="POST">
		<input type="text" name="pseudo">
		<input type="text" name="comment">
		<input type="submit">
	</form>
</body>
</html>