<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Loterie 3Wacademy</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="lottery.css">
</head>
<body>
    <header>
        <h1>Loterie 3WAcademy</h1>
    </header>

    <main>
        <p>Le résultat du tirage de la loterie 3WAcademy est : <em><?= implode(', ', $lotteryDraw); ?></em></p>
    </main>
</body>
</html>