<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<form action="<?= $requestUrl ?>/signup" method="post">
    <h2><i class="fas fa-user"></i> Créer un compte</h2>
    <fieldset>
        <legend><i class="fas fa-book"></i> Identité et coordonnées</legend>

        <ul>
            <li>
                <label for="lastname">Nom</label>
                <input type="text" name="lastName">
            </li>
            <li>
                <label for="firstname">Prénom</label>
                <input type="text" name="firstName">
            </li>
            <li>
                <label for="birthday">Date de naissance</label>
                <select id="birthday" name="day">
                    <?php for($day = 1; $day <= 31; $day++): ?>
                        <option value="<?= $day ?>"><?= $day ?></option>
                    <?php endfor ?>
                </select>
                <span>/</span>
                <select name="month">
                    <option value="1">Janvier</option>
                    <option value="2">Février</option>
                    <option value="3">Mars</option>
                    <option value="4">Avril</option>
                    <option value="5">Mai</option>
                    <option value="6">Juin</option>
                    <option value="7">Juillet</option>
                    <option value="8">Août</option>
                    <option value="9">Septembre</option>
                    <option value="10">Octobre</option>
                    <option value="11">Novembre</option>
                    <option value="12">Décembre</option>
                </select>
                <span>/</span>
                <select name="year">
                    <?php for($year = 1940; $year < date("Y"); $year++): ?>
                        <option value="<?= $year ?>"><?= $year ?></option>
                    <?php endfor ?>
                </select>
            </li>
            <li>
                <label for="address">Adresse</label>
                <textarea name="address" id="address" cols="30" rows="10"></textarea>
            </li>
            <li>
                <label for="city">Ville</label>
                <input type="text" name="city">
            </li>
            <li>
                <label for="cp">Code Postal</label>
                <input type="text" name="zipCode">
            </li>
            <li>
                <label for="phone">Téléphone</label>
                <input type="tel" name="phone">
            </li>
        </ul>
    </fieldset>
    
    <fieldset>
        <legend><i class="fas fa-lock"></i> Information d'authentification</legend>
        <ul>
            <li>
                <label for="mail">Adresse Mail</label>
                <input type="text" name="mail">
            </li>
            <li>
                <label for="password">Mot de passe</label>
                <input type="password" name="password">
            </li>
        </ul>
    </fieldset>
    <button type="submit" class="signup">Valider</button>

    <button type="submit" class="cancel">Annuler</button>
</form>

