<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">

    <!-- Feuilles de styles de l'application -->

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>



<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
        <?php if(isset($_SESSION["mail"])):?>
            <p> Bonjour <?=$_SESSION["firstName"]." ".$_SESSION["lastName"];?></p>
            <?php if($_SESSION["role"] == "admin"): ?>
                <button><a href="<?=$requestUrl?>/admin"><i class="fas fa-cogs"></i> Administration</a></button>


            <?php endif;?>

            <!--Bouton de déconnexion -->
            <button type="button" class="login"><a href="<?=$requestUrl?>/disconnect">Deconnexion</a></button>

            <!--Bouton de réservation -->
            <button type="button" class="login"><a href="<?=$requestUrl?>/booking">Réserver</a></button>

            <!--Bouton de commande -->
            <button type="button" class="login"><a href="<?=$requestUrl?>/order">Commander</a></button>
        <?php else : ?>

            <!--Bouton de connexion -->
            <button type="button" class="login"><a href="<?=$requestUrl?>/login">Connexion</a></button>

            <!--Bouton de créer un compte -->
            <button type="button" class="signup"><a href="<?=$requestUrl?>/signup">Créer un compte</a></button>
        <?php endif;?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->

    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" height="63" width="57" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" height="63" width="57" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" height="63" width="57" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>